### ISSUE TITLE
kendala pada saat install di windows 7

### ISSUE THREAD

**Issue by kakferryse** [nafiesl/arisan#16]
Saya sudah melakukan proses install dari panduan
langkah 1-7 berhasil.
Langkah 8 muncul pesan error ini
![Screenshot_9](https://user-images.githubusercontent.com/41139461/84595803-1df91280-ae84-11ea-89a9-ecee6ab85a27.jpg)
sehingga tidak bisa melakukan langkah selanjutnya,.
lalu sya coba lanjut ke tahap terakhir tahaap 9 dan berhasil akses url tetapi setelah register hasilnya error seperti ini
![Screenshot_10](https://user-images.githubusercontent.com/41139461/84595940-00787880-ae85-11ea-8eac-4cb86a69d508.jpg)

**Comment by nafiesl** [comment]
Halo mas @kakferryse kalau dilihat dari errornya, sepertinya database yang mas gunakan tidak compatilbe dengan [requirement di point ke 2](https://github.com/nafiesl/arisan#spesifikasi-minimum-server): MySQL 5.7 atau MariaDB 10.2.

Tapi itu bisa kita atasi dengan mengubah fille config database:
https://github.com/nafiesl/arisan/blob/master/config/database.php#L50-L51

Dari:
```
'charset' => 'utf8mb4',
'collation' => 'utf8mb4_unicode_ci',
```
Menjadi
```
'charset' => 'utf8',
'collation' => 'utf8_unicode_ci',
```

Kemudian coba mas ulangi langkah install ke 8:
https://github.com/nafiesl/arisan#tahap-install

Atau jalankan perintah ini:
```
$ php artisan migrate:fresh
```

**Comment by kakferryse** [comment]
setelah saya coba msh ttp tdk bisa, muncul error sprti ini
![Screenshot_1](https://user-images.githubusercontent.com/41139461/84596426-e0968400-ae87-11ea-80cc-5d91f5672e0a.jpg)
oia mas, sekalian cara ilangin warning module ssl nya bgmna yah??

**Comment by nafiesl** [comment]
Terkait error **yang collation**:
Coba databasenya mas kosongkan dulu sehingga tidak ada tabel lagi di dalamnya. Lalu jalankan php artisan migrate.


Terkait warning **Module openssl**:
Ini out of scope dari project ini, tapi saya bantu googling, keyword: "Warning module openssl already loaded windows xampp"
Ketemu solusi ini, mungkin bisa dicoba.
https://stackoverflow.com/questions/36675348/xampp-warning-module-openssl-already-loaded-in-line-0#answer-36675367

**Comment by kakferryse** [comment]
setelah saya baca, ternyata sdh ada issue 2thn lalu dgn case yg sama..hahaa tadi knp ga terbaca yah pas mau buat issue ckckk.
tp ttp gabisa mas, error nya msh sama.. pdhl sdh drop tabel nya

**Comment by nafiesl** [comment]
O iya, saya rasanya juga ingat pernah ada yang lapor, tapi saya cari2 lupa di project yang mana. Ternyata ini ya #2. :grinning:
