### ISSUE TITLE
Celah XSS dari query string

### ISSUE THREAD

**Issue by nafiesl** [nafiesl/arisan#3]
Ditemukan celh XSS dari query string saat mencoba setting pertemuan.

Contoh url:
```
/groups/1/meetings?number=<script>alert("XSS");</script>&action=set-meeting
```
![shutter_20180704-010](https://user-images.githubusercontent.com/8721551/42273548-0e554dba-7fbc-11e8-9095-2b6a069df2c3.jpg)

**Comment by ad3n** [comment]
Ini di controller mana ya? biar tak bantuin

**Comment by nafiesl** [comment]
Conttollernya yang ini mas Sur: `Groups/MeetingsController.php´

Tetapi yang perlu diperbaiki bagian di file ini, baris 1 s/d 3:
[meetings/partials/set-meeting.blade.php](https://github.com/nafiesl/arisan/blob/master/resources/views/meetings/partials/set-meeting.blade.php).

Seharusnya variabel itu di proses di controller nya dulu sih, biar pas masuk view dia sudah pasti dalam int.

Terima kasih mas Sur.

**Comment by ad3n** [comment]
mayan... bentar lagi nampang di contributor wkwkwk
