### ISSUE TITLE
User bisa mengakses detail grup dan pertemuan yang bukan grupnya

### ISSUE THREAD

**Issue by nafiesl** [nafiesl/arisan#4]
Saat ini user bebas melihat grup dengan mengubah ID Grup di URL, dan juga melihat detail pertemuan walaupun dia tidak tergabung dalam grup tersebut, misal:

`/groups/1`, `/groups/2`, `/groups/6/meetings`, `/meetings/7`.

Seharusnya user **hanya boleh** melihat detail **grup** dan **pertemuan** dimana dia bergabung. Atau jika grup itu dikelolanya (grup creator).

**Comment by ad3n** [comment]
Pakai middleware biar existing code ga perlu diubah... (saran)

**Comment by nafiesl** [comment]
Rencana nanti akan gunakan laravel auhtorization mas @ad3n, jadi bisa diatur di GroupPolicy objectnya.
